language: android

android:
  components:
    - tools
    - build-tools-22.0.1
    - android-23
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support

script:
  ./gradlew assembleRelease
