language: android

android:
  components:
    - tools
    - build-tools-24.0.1
    - android-24
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support

jdk:
  - oraclejdk8
  
script:
  ./gradlew assembleRelease
