language: android

android:
  components:
    - tools
    - build-tools-25.0.0
    - android-25
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support

jdk:
  - oraclejdk8
  
script:
  ./gradlew assembleRelease
